import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'

const IndexPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next Auth0 SSR App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={styles.container}>
        <p>Welcome!!</p>
      </div>
    </>
  )
}

export default IndexPage
